//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExamination
    {
        public int Id { get; set; }
        public Nullable<int> FKPatient { get; set; }
        public Nullable<int> FKDoctor { get; set; }
        public Nullable<int> NumberOfTries { get; set; }
    
        public virtual tblClinicDoctor tblClinicDoctor { get; set; }
        public virtual tblClinicPatient tblClinicPatient { get; set; }
    }
}
