//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMedicalInstitution
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> ConstructionDate { get; set; }
        public string Owner { get; set; }
        public string Address { get; set; }
        public Nullable<int> FloorsNumber { get; set; }
        public Nullable<int> PersonsPerFloor { get; set; }
        public Nullable<bool> Terrace { get; set; }
        public Nullable<bool> Yard { get; set; }
        public Nullable<int> AmbulanceAccessPointNumber { get; set; }
        public Nullable<int> DisabledPatitentAccessPointNumber { get; set; }
    }
}
